import { z } from "zod";

const color = z
  .string()
  .regex(
    /^(|#[0-9a-fA-F]{6}|theme:(background|surface|foreground|muted|border|primary|onPrimary|soft))$/,
  );
const anchor = z.enum(["start", "center", "end", "stretch", "scale"]);
export const designFields = {
  mode: z.enum(["flow", "free"]).optional(),
  x: z.number().finite().min(-100000).max(100000).optional(),
  y: z.number().finite().min(-100000).max(100000).optional(),
  heightMode: z.enum(["auto", "fixed"]).optional(),
  height: z.number().min(1).max(20000).optional(),
  rotation: z.number().min(-360).max(360).optional(),
  ratioLocked: z.boolean().optional(),
  clip: z.boolean().optional(),
  anchorX: anchor.optional(),
  anchorY: anchor.optional(),
  basisWidth: z.number().min(1).max(20000).optional(),
  basisHeight: z.number().min(1).max(20000).optional(),
  fillColor: color.optional(),
  textColor: color.optional(),
  strokeColor: color.optional(),
  strokeWidth: z.number().min(0).max(30).optional(),
  cornerRadius: z.number().min(-1).max(1000).optional(),
  opacity: z.number().min(0).max(1).optional(),
  shadow: z.enum(["inherit", "none", "soft", "medium", "strong"]).optional(),
  fontSize: z.number().min(0).max(400).optional(),
  fontWeight: z.number().int().min(0).max(900).optional(),
  lineHeight: z.number().min(0).max(4).optional(),
  letterSpacing: z.number().min(-20).max(100).optional(),
  textAlign: z.enum(["inherit", "left", "center", "right"]).optional(),
  imageFit: z.enum(["cover", "contain"]).optional(),
  imageX: z.number().min(0).max(100).optional(),
  imageY: z.number().min(0).max(100).optional(),
};
export const DESIGN_DEFAULTS = {
  mode: "flow",
  x: 0,
  y: 0,
  heightMode: "auto",
  height: 240,
  rotation: 0,
  ratioLocked: false,
  clip: false,
  anchorX: "start",
  anchorY: "start",
  basisWidth: 1440,
  basisHeight: 920,
  fillColor: "",
  textColor: "",
  strokeColor: "",
  strokeWidth: 0,
  cornerRadius: -1,
  opacity: 1,
  shadow: "inherit",
  fontSize: 0,
  fontWeight: 0,
  lineHeight: 0,
  letterSpacing: 0,
  textAlign: "inherit",
  imageFit: "cover",
  imageX: 50,
  imageY: 50,
} as const;

export const APPEARANCE_KEYS = [
  "fillColor",
  "textColor",
  "strokeColor",
  "strokeWidth",
  "cornerRadius",
  "opacity",
  "shadow",
  "fontSize",
  "fontWeight",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "imageFit",
  "imageX",
  "imageY",
] as const;
