import type { Definition, Field } from "./catalog";
import { GALLERY_ITEMS, HOTSPOT_ITEMS } from "./image-collections";
const source = (
  key: string,
  label: string,
  assetKinds: Field["assetKinds"],
): Field => ({ key, label, type: "asset", assetKinds });
const number = (key: string, label: string, max = 86400): Field => ({
  key,
  label,
  type: "number",
  min: 0,
  max,
});
export const MEDIA_CATALOG: Definition[] = [
  {
    id: "image-lightbox",
    name: "사진 확대 보기",
    category: "미디어",
    source: "Prompt Studio",
    description: "작품을 크게 열고 키보드로 넘기는 사진 컬렉션",
    defaults: { title: "가까이 들여다보기" },
    fields: [{ key: "title", label: "제목", type: "text" }],
    collections: { items: GALLERY_ITEMS },
  },
  {
    id: "image-compare",
    name: "이미지 비교",
    category: "미디어",
    source: "Prompt Studio",
    description: "두 사진을 슬라이더로 겹쳐 비교",
    defaults: {
      title: "변화의 순간",
      before: "",
      after: "",
      beforeLabel: "Before",
      afterLabel: "After",
      position: 50,
      ratio: "16/9",
    },
    fields: [
      { key: "title", label: "제목", type: "text" },
      source("before", "이전 이미지", ["image"]),
      source("after", "이후 이미지", ["image"]),
      { key: "beforeLabel", label: "이전 설명", type: "text" },
      { key: "afterLabel", label: "이후 설명", type: "text" },
      number("position", "시작 분할 위치 · %", 100),
      {
        key: "ratio",
        label: "비율",
        type: "select",
        options: ["16/9", "4/3", "1/1"],
      },
    ],
  },
  {
    id: "image-hotspot",
    name: "이미지 설명 지점",
    category: "미디어",
    source: "Prompt Studio",
    description: "사진의 위치를 표시하고 세부 설명을 펼침",
    defaults: {
      title: "디테일을 발견하세요",
      src: "",
      alt: "제품의 전체 모습",
      ratio: "16/9",
    },
    fields: [
      { key: "title", label: "제목", type: "text" },
      source("src", "이미지", ["image"]),
      { key: "alt", label: "대체 설명", type: "text" },
      {
        key: "ratio",
        label: "비율",
        type: "select",
        options: ["16/9", "4/3", "1/1"],
      },
    ],
    collections: { items: HOTSPOT_ITEMS },
  },
  {
    id: "video-player",
    optionalProps: ["editableControls"],
    name: "영상 플레이어",
    category: "미디어",
    source: "Prompt Studio",
    description: "영상과 포스터·자막을 넣고 재생 구간을 조절",
    defaults: {
      title: "우리의 다음 장면",
      src: "",
      poster: "",
      captions: "",
      transcript: "",
      ratio: "16/9",
      fit: "contain",
      start: 0,
      end: 0,
      loop: false,
      muted: true,
      autoplay: false,
      editableControls: true,
    },
    fields: [
      { key: "title", label: "영상 제목", type: "text" },
      source("src", "영상", ["video"]),
      source("poster", "대표 이미지", ["image"]),
      source("captions", "한국어 자막 · VTT", ["captions"]),
      { key: "transcript", label: "영상 대본", type: "textarea" },
      {
        key: "editableControls",
        label: "재생 버튼·막대 개별 편집",
        type: "toggle",
      },
      {
        key: "ratio",
        label: "화면 비율",
        type: "select",
        options: ["16/9", "4/3", "1/1", "9/16", "21/9"],
      },
      {
        key: "fit",
        label: "영상 맞춤",
        type: "select",
        options: ["contain", "cover"],
      },
      number("start", "시작 시간 · 초"),
      number("end", "종료 시간 · 0은 끝까지"),
      { key: "loop", label: "구간 반복", type: "toggle" },
      { key: "muted", label: "처음에는 음소거", type: "toggle" },
      {
        key: "autoplay",
        label: "화면에 들어오면 자동 재생 시도",
        type: "toggle",
      },
    ],
  },
  {
    id: "audio-player",
    optionalProps: ["editableControls"],
    name: "오디오 플레이어",
    category: "미디어",
    source: "Prompt Studio",
    description: "음성과 음악, 표지와 대본을 함께 소개",
    defaults: {
      title: "새로운 이야기를 들어보세요",
      src: "",
      poster: "",
      transcript: "",
      start: 0,
      end: 0,
      loop: false,
      editableControls: true,
    },
    fields: [
      { key: "title", label: "오디오 제목", type: "text" },
      source("src", "오디오", ["audio"]),
      source("poster", "표지 이미지", ["image"]),
      { key: "transcript", label: "오디오 대본", type: "textarea" },
      {
        key: "editableControls",
        label: "재생 버튼·막대 개별 편집",
        type: "toggle",
      },
      number("start", "시작 시간 · 초"),
      number("end", "종료 시간 · 0은 끝까지"),
      { key: "loop", label: "구간 반복", type: "toggle" },
    ],
  },
];
