export const MORE_CSS = `
.ui-more-icon{width:100%;height:100%;color:var(--node-color,var(--ui-primary))}.ui-more-spacer{width:100%;height:100%;min-height:1px}
.ui-more-quantity{display:flex;align-items:center;justify-content:space-between;gap:16px}.ui-more-quantity>div{display:flex;align-items:center;border:1px solid var(--ui-border);border-radius:var(--ui-radius);overflow:hidden}.ui-more-quantity button{width:40px;height:40px;background:var(--ui-surface);color:var(--ui-foreground);font-size:20px}.ui-more-quantity output{min-width:42px;text-align:center}
.ui-more-rating{border:0;padding:0;margin:0}.ui-more-rating legend{font-size:12px;color:var(--ui-muted);margin-bottom:4px}.ui-more-rating>div{display:flex;align-items:center;gap:4px}.ui-more-rating label{position:relative;cursor:pointer}.ui-more-rating input{position:absolute;opacity:0;inset:0;width:100%;height:100%;margin:0;cursor:pointer}.ui-more-rating span{font-size:26px;color:var(--ui-border)}.ui-more-rating [data-active=true]{color:var(--ui-primary)}.ui-more-rating input:focus-visible+span{outline:2px solid var(--ui-primary);outline-offset:2px}.ui-more-rating output{font-size:12px;margin-left:12px;color:var(--ui-muted)}
.ui-more-segmented{display:flex;flex-wrap:wrap;gap:4px;padding:5px;background:var(--ui-soft);border-radius:var(--ui-radius)}.ui-more-segmented button{flex:1;padding:10px 14px;white-space:nowrap;background:transparent;border-radius:calc(var(--ui-radius)*.7);color:var(--ui-muted)}.ui-more-segmented [aria-pressed=true]{background:var(--ui-surface);color:var(--ui-primary);box-shadow:0 2px 5px #0000000a}
.ui-more-tags>label{display:block;margin-bottom:8px;font-weight:600}.ui-more-tags>div{display:flex;flex-wrap:wrap;align-items:center;gap:8px;border:1px solid var(--ui-border);padding:12px;border-radius:var(--ui-radius);background:var(--ui-surface)}.ui-more-tags span{display:flex;align-items:center;gap:6px;background:var(--ui-soft);color:var(--ui-primary);padding:3px 8px;border-radius:5px;font-size:12px}.ui-more-tags button{background:none;color:inherit;font-size:17px}.ui-more-tags input{border:0;background:transparent;color:var(--ui-foreground);min-width:100px;flex:1;padding:5px;width:100%}
.ui-more-color{display:flex;align-items:center;justify-content:space-between;gap:16px}.ui-more-color>span{display:flex;align-items:center;gap:12px}.ui-more-color input{width:44px;height:36px;border:1px solid var(--ui-border);border-radius:6px;padding:3px;background:var(--ui-surface)}.ui-more-color output{font-family:monospace;font-size:12px}
.ui-more-upload{padding:32px;text-align:center;border:2px dashed var(--ui-border);border-radius:var(--ui-radius);background:var(--ui-surface)}.ui-more-upload label{font-size:17px;font-weight:650}.ui-more-upload p{font-size:13px;color:var(--ui-muted);margin:10px 0 20px}.ui-more-upload input{max-width:100%;font-size:12px}.ui-more-upload input::file-selector-button{border:0;background:var(--ui-primary);color:var(--ui-onPrimary);padding:10px 14px;border-radius:6px;margin-right:12px;cursor:pointer}.ui-more-upload ul{list-style:none;padding:0;font-size:12px;overflow-wrap:anywhere}.ui-more-upload small{display:block;font-size:11px;color:var(--ui-muted);margin-top:16px}
.ui-more-meter{padding:24px;border:1px solid var(--ui-border);border-radius:var(--ui-radius);background:var(--ui-surface)}.ui-more-meter label{display:block;font-weight:600}.ui-more-meter strong{display:block;font-size:28px;margin:15px 0 8px}.ui-more-meter small{font-size:13px;font-weight:400;color:var(--ui-muted)}.ui-more-meter meter{width:100%;height:18px;accent-color:var(--ui-primary)}.ui-more-meter p{font-size:12px;color:var(--ui-muted);margin-top:8px}
`;
