export const DESIGN_FAMILIES = [
  { id: "minimal", name: "미니멀", color: "#18181b", surface: "#ffffff" },
  { id: "soft", name: "소프트 SaaS", color: "#6366f1", surface: "#eef2ff" },
  { id: "outline", name: "테두리", color: "#334155", surface: "#ffffff" },
  { id: "brutal", name: "뉴브루탈", color: "#17201b", surface: "#d9f968" },
  { id: "editorial", name: "에디토리얼", color: "#704e3b", surface: "#faf5ec" },
  { id: "glass", name: "글래스", color: "#576d97", surface: "#e5edf7" },
  { id: "dark", name: "다크 테크", color: "#b5f5d1", surface: "#162027" },
  { id: "colorful", name: "컬러풀", color: "#9333ea", surface: "#fce7f3" },
] as const;
export type DesignFamily = (typeof DESIGN_FAMILIES)[number]["id"];
export const PRESET_COMPONENTS = [
  "button",
  "badge",
  "input",
  "checkbox",
  "switch",
  "select",
  "card",
  "feature",
  "stat",
  "tabs",
  "accordion",
  "alert",
  "table",
  "pricing",
  "testimonial",
  "empty",
  "navbar",
  "hero",
  "sidebar",
  "cta",
  "footer",
  "avatar",
  "product",
  "search",
] as const;
export const MOTIONS = [
  ["none", "효과 없음"],
  ["fade", "부드럽게 등장"],
  ["slide", "아래에서 등장"],
  ["scale", "확대 등장"],
  ["float", "가볍게 떠 있기"],
  ["pulse", "은은한 강조"],
  ["shimmer", "빛이 흐르는 표면"],
  ["gradient", "움직이는 그라디언트"],
  ["border", "테두리 빛"],
  ["tilt", "호버 기울기"],
  ["lift", "호버 떠오름"],
  ["reveal", "텍스트 펼침"],
  ["glow", "은은한 빛"],
  ["words", "단어별 등장"],
  ["mask", "마스크로 열기"],
  ["parallax", "스크롤 깊이 이동"],
  ["scroll-zoom", "스크롤 확대"],
] as const;
export type MotionId = (typeof MOTIONS)[number][0];
export const NEW_COMPONENT_IDS = [
  "combobox",
  "multi-select",
  "input-otp",
  "input-group",
  "date-range-picker",
  "password-input",
  "color-swatch",
  "toggle-group",
  "command-palette",
  "context-menu",
  "menubar",
  "mega-menu",
  "popover",
  "hover-card",
  "sheet",
  "drawer",
  "alert-dialog",
  "carousel",
  "tree-view",
  "file-manager",
  "code-block",
  "terminal",
  "line-chart",
  "area-chart",
  "radar-chart",
  "heatmap",
  "resizable-panels",
  "scroll-area",
  "toggle-button",
  "copy-button",
] as const;
export const visualPresetCount =
  PRESET_COMPONENTS.length * DESIGN_FAMILIES.length;
