export const VISUAL_CSS = `
:where(.ui-node[data-family]:not([data-family=legacy])){--ui-radius:12px;--ui-primary:#18181b;--ui-onPrimary:#fff;--ui-foreground:#18181b;--ui-muted:#687080;--ui-border:#dce0e5;--ui-surface:#fff;--ui-soft:#f1f3f5;color:var(--ui-foreground)}
.ui-node[data-family=soft]{--ui-primary:#4f46e5;--ui-soft:#eef2ff;--ui-radius:20px;--studio-shadow:0 8px 28px #6366f119}
.ui-node[data-family=outline]{--ui-primary:#334155;--ui-border:#64748b;--ui-radius:4px;--studio-shadow:none}
.ui-node[data-family=brutal]{--ui-primary:#d9f968;--ui-onPrimary:#17201b;--ui-soft:#f5fcd9;--ui-border:#17201b;--ui-radius:0px;--studio-shadow:4px 4px 0 #17201b;font-weight:600}
.ui-node[data-family=editorial]{--ui-primary:#704e3b;--ui-surface:#faf5ec;--ui-soft:#efe6d9;--ui-border:#d8c9b6;--ui-radius:2px;font-family:Georgia,'Noto Serif KR',serif}
.ui-node[data-family=glass]{--ui-primary:#576d97;--ui-surface:#edf4facc;--ui-soft:#dfe9f4;--ui-border:#fff;--ui-radius:24px;--studio-shadow:0 10px 32px #576d9726;backdrop-filter:blur(14px)}
.ui-node[data-family=dark]{--ui-primary:#b5f5d1;--ui-onPrimary:#162027;--ui-foreground:#f1f7f4;--ui-muted:#a0b4aa;--ui-border:#3d5147;--ui-surface:#162027;--ui-soft:#243c30;--ui-radius:10px}
.ui-node[data-family=colorful]{--ui-primary:#9333ea;--ui-soft:#fce7f3;--ui-border:#e9c4f6;--ui-surface:#fff6fd;--ui-radius:28px;--studio-shadow:0 8px 0 #f9bce7}
.ui-node[data-family]:not([data-family=legacy]):not([data-custom-radius=true])> :is(.ui-button,.studio-component,[data-slot=button]),.ui-node[data-family]:not([data-family=legacy]):not([data-custom-radius=true]).ui-card{border-radius:var(--ui-radius)}
.ui-node[data-family]:not([data-family=legacy]):not([data-custom-shadow=true])>:first-child:not(.studio-component),.ui-node[data-family]:not([data-family=legacy]):not([data-custom-shadow=true])>.studio-component [data-slot=button]{box-shadow:var(--studio-shadow,none)}
.ui-node[data-family]:not([data-family=legacy]).ui-container{background:var(--ui-surface);border-color:var(--ui-border);color:var(--ui-foreground)}
.ui-node[data-family=brutal] :is(.ui-button,input,[data-slot=button],[data-slot=input]){border:2px solid var(--ui-border)}
.ui-node[data-family=outline] :is(.ui-button,[data-slot=button]){background:transparent;color:var(--ui-primary);border:1px solid var(--ui-primary)}
.studio-component{font-size:14px;line-height:1.5;min-width:0;color:var(--ui-foreground);background:var(--ui-surface)}
.ui-node[data-component=button]:is([data-width-mode=fixed],[data-width-mode=fill])>.studio-component>[data-slot=button]{width:100%}
.studio-section-heading{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}
.studio-component button{cursor:pointer}.studio-component button:disabled{cursor:not-allowed}.studio-component svg{flex-shrink:0}
.studio-component h3,.studio-component p{margin:0}.studio-component label,.studio-field{display:flex;flex-direction:column;gap:8px}.studio-field{border:0;padding:0;min-width:0}
.studio-field>label,.studio-field>span:first-child{font-size:13px;font-weight:600}.studio-field>p,.studio-status{font-size:12px;color:var(--ui-muted)}
.studio-input-group{display:flex;align-items:center;gap:10px}.studio-input-group input{min-width:0;flex:1}.studio-status:empty{display:none}.studio-status{display:block;margin-top:8px}
.studio-swatches{display:flex;gap:10px;flex-wrap:wrap}.studio-swatches button{width:38px;height:38px;border:2px solid var(--ui-border);border-radius:50%;display:grid;place-items:center}.studio-swatches button[aria-pressed=true]{outline:2px solid var(--ui-primary);outline-offset:3px}
.studio-context-target{display:grid;place-items:center;min-height:160px;padding:24px;border:1px dashed var(--ui-border);border-radius:12px}
.studio-mega{display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap}.studio-mega-links{width:340px;max-width:80vw;list-style:none;padding:12px;display:grid;gap:8px}.studio-mega-links button{display:grid;text-align:left;padding:14px;width:100%;border-radius:8px}.studio-mega-links button:hover{background:var(--ui-soft)}.studio-mega-links small{color:var(--ui-muted)}
.studio-carousel{padding:12px 44px}.studio-slide{display:flex;flex-direction:column;justify-content:center;gap:20px;min-height:180px;padding:32px;background:var(--ui-soft);border:1px solid var(--ui-border);border-radius:var(--ui-radius)}.studio-slide strong{font-size:32px;color:var(--ui-primary)}
.studio-tree,.studio-files,.studio-chart,.studio-code{padding:20px;border:1px solid var(--ui-border);border-radius:var(--ui-radius);background:var(--ui-surface)}.studio-tree summary,.studio-tree button{display:flex;align-items:center;gap:8px;padding:10px;text-align:left}.studio-tree button{margin-left:24px}.studio-tree svg{width:16px;height:16px}.studio-tree button[aria-pressed=true]{background:var(--ui-soft)}
.studio-file-toolbar{display:flex;gap:8px;align-items:center;margin:16px 0}.studio-file-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px}.studio-file-grid.list{grid-template-columns:1fr}.studio-file-grid button{display:flex;align-items:center;flex-wrap:wrap;gap:10px;text-align:left;padding:16px;border:1px solid var(--ui-border);border-radius:10px}.studio-file-grid small{color:var(--ui-muted)}.studio-file-grid button[aria-pressed=true]{background:var(--ui-soft);border-color:var(--ui-primary)}
.studio-code header{display:flex;align-items:center;justify-content:space-between;gap:12px}.studio-code pre{overflow:auto;white-space:pre;padding:20px 0;margin:0;font:13px/1.8 ui-monospace,monospace}.studio-terminal{background:#162027;color:#b5f5d1}.studio-chart svg{width:100%;height:auto;max-height:320px}.studio-chart-legend{display:flex;flex-wrap:wrap;gap:14px;font-size:12px}.studio-heatmap{display:grid;grid-template-columns:repeat(auto-fit,minmax(80px,1fr));gap:6px;margin:16px 0}.studio-heatmap>div{display:flex;flex-direction:column;padding:12px;border-radius:6px}
.studio-panel{padding:24px;min-height:180px;background:var(--ui-soft)}.studio-scroll-row{padding:12px 16px;border-bottom:1px solid var(--ui-border)}
.ui-node[data-motion=fade]{animation:studio-fade .7s both}.ui-node[data-motion=slide]{animation:studio-slide .7s both}.ui-node[data-motion=scale]{animation:studio-scale .6s both}.ui-node[data-motion=float]{animation:studio-float 3s ease-in-out infinite}.ui-node[data-motion=pulse]{animation:studio-pulse 2s ease-in-out infinite}.ui-node[data-motion=shimmer]{background:linear-gradient(100deg,transparent 20%,#ffffff66 50%,transparent 80%);background-size:250% 100%;animation:studio-gradient 3s linear infinite}.ui-node[data-motion=gradient]{background:linear-gradient(120deg,var(--ui-soft),var(--ui-surface),var(--ui-soft));background-size:250% 100%;animation:studio-gradient 5s ease infinite}.ui-node[data-motion=border]{animation:studio-border 2.5s infinite}.ui-node[data-motion=reveal]{animation:studio-reveal .8s both}.ui-node[data-motion=glow]{animation:studio-glow 3s infinite}.ui-node[data-motion=lift],.ui-node[data-motion=tilt]{transition:translate .25s,rotate .25s}.ui-root:not(.ui-edit) .ui-node[data-motion=lift]:hover{translate:0 -6px}.ui-root:not(.ui-edit) .ui-node[data-motion=tilt]:hover{rotate:2deg}
.ui-edit [data-motion]{animation:none!important;transition:none!important}.ui-node[data-motion-visible=false]{animation-play-state:paused!important}
@keyframes studio-fade{from{opacity:0}to{opacity:var(--motion-opacity,1)}}@keyframes studio-slide{from{opacity:0;translate:0 20px}to{opacity:var(--motion-opacity,1);translate:0 0}}@keyframes studio-scale{from{opacity:0;scale:.92}to{opacity:var(--motion-opacity,1);scale:1}}@keyframes studio-float{50%{translate:0 -8px}}@keyframes studio-pulse{50%{opacity:calc(var(--motion-opacity,1)*.7)}}@keyframes studio-gradient{50%{background-position:100% 0}}@keyframes studio-border{50%{outline:2px solid var(--ui-primary);outline-offset:3px}}@keyframes studio-reveal{from{clip-path:inset(0 100% 0 0)}to{clip-path:inset(0)}}@keyframes studio-glow{50%{box-shadow:0 0 24px color-mix(in srgb,var(--ui-primary) 40%,transparent)}}
@media(prefers-reduced-motion:reduce){.ui-node[data-motion]{animation:none!important;transition:none!important;translate:none!important;rotate:none!important}}
.design-move-label{position:absolute;bottom:100%;left:0;white-space:nowrap;border:0;background:#5b64e8;color:#fff;padding:4px 7px;border-radius:4px 4px 0 0;pointer-events:auto;cursor:grab;font:11px/1.3 sans-serif}.design-drop{border:2px solid #5b64e8!important;background:#5b64e814!important}
`;
